/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('./../src/components/auto/a-button.vue')['default']
    IconCustomContact: typeof import('~icons/custom/contact')['default']
    IconCustomEmojiBoy: typeof import('~icons/custom/emoji-boy')['default']
    IconCustomTwemojiBoy: typeof import('~icons/custom/twemoji-boy')['default']
    IconEpAccountCircle: typeof import('~icons/ep/account-circle')['default']
    IconMaterialSymbols3kPlusOutlineSharp: typeof import('~icons/material-symbols/3k-plus-outline-sharp')['default']
    IconTwemoji3rdPlaceMedal: typeof import('~icons/twemoji/3rd-place-medal')['default']
    IconTwemojiBentoBox: typeof import('~icons/twemoji/bento-box')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
